### ISSUE TITLE
Update for release version? 

### ISSUE THREAD

**Issue by whispertante** [MontagueM/NewWorldUnpacker#9]
Hi, 
thanks for your effort. Unfortunately, it seems to be not working for the release version. 
For instance, the script returns "Unpack done" for assets/DataStrm-part2.pak, but the output folder is still empty.
Other .paks like /assets/levels/main_menu/level.pak are extractable with WinRAR but not with this tool (returns error for some files).

Could you have a look and maybe update? Thanks!

**Comment by whispertante** [comment]
I made the fix by myself and made a pull request: 
https://github.com/MontagueM/NewWorldUnpacker/pull/10

Tested and works with 0x9 bitflag

**Comment by MontagueM** [comment]
Fixed.
